# Documentation: https://docs.getdbt.com/docs/get-started/connection-profiles

wide_world_importers_dbt:
  outputs:
    dev:
      project: project-github-471211
      keyfile: conf/project-github-471211-29c865e9e4a9.json
      dataset: wide_world_importers_dwh
      location: asia-southeast1
      type: bigquery
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      priority: interactive
      threads: 4
  target: dev
